name: territory-conquest-economy
version: '${project.version}'
main: the.david.Territory_conquest_economy
api-version: 1.19
commands:
  tce:
    usage: "/tce"
    description: "Terricory Conquest's economy plugin command"
    permission: "op"
  points:
    usage: "/points"
    description: "get the Terricory Conquest's point informations"

softdepend: [PlaceholderAPI]
