name: territory-conquest-economy
version: '${project.version}'
main: the.david.Territory_conquest_economy
api-version: 1.19
commands:
  tce:
    usage: "/tce"
    description: "Terricory Conquest's economy plugin command"
    permission: "op"

softdepend: [PlaceholderAPI]
